### ISSUE TITLE
installing mopidy-spotify fails

### ISSUE THREAD

**Issue by Comradin** [mopidy/homebrew-mopidy#2]
Hello,

it's not possible to install the mopidy-spotify package:

```
brew install mopidy-spotify
==> Installing mopidy-spotify from mopidy/homebrew-mopidy
Error: You must `brew link gsettings-desktop-schemas' before mopidy-spotify can be installed
```

Ok, no problem, lets do the linking:

```
brew link gsettings-desktop-schemas
Linking /usr/local/Cellar/gsettings-desktop-schemas/3.14.0...
Error: Could not symlink share/glib-2.0/schemas/gschemas.compiled
Target /usr/local/share/glib-2.0/schemas/gschemas.compiled
is a symlink belonging to gst-plugins-bad010. You can unlink it:
brew unlink gst-plugins-bad010
```

To force the link and overwrite all conflicting files:

```
brew link --overwrite gsettings-desktop-schemas

To list all files that would be deleted:
brew link --overwrite --dry-run gsettings-desktop-schemas
```

I'll follow the unlink advice for the gst-plugins-bad010 and link the desktop-schemas:

```
brew unlink gst-plugins-bad010
Unlinking /usr/local/Cellar/gst-plugins-bad010/0.10.23... 156 symlinks removed
brew link gsettings-desktop-schemas
Linking /usr/local/Cellar/gsettings-desktop-schemas/3.14.0... 78 symlinks created
```

And now I everything starts again, this time with the message to link the just unlink'ed package:

```
brew install mopidy-spotify
==> Installing mopidy-spotify from mopidy/homebrew-mopidy
Error: You must `brew link gst-plugins-bad010' before mopidy-spotify can be installed
```

I am caught in a circular dependency. System is OS X 10.10.2. Just did a fresh brew update before tap'ing the mopidy formula.

**Comment by jodal** [comment]
There's a conflict between the formulas `gsettings-desktop-schemas` and `gst-plugins-bad010` where both try to write the same file. The "solution" is to have both linked, but let one of them overwrite the conflicting file. I don't think it matters much which one gets to overwrite the file.

Others have done this with success, ref https://discuss.mopidy.com/t/brew-link-fails-on-mpd-installaion/470.

**Comment by jodal** [comment]
To achieve a proper solution here, please open a bug with the conflicting formulas so one of them can be updated to avoid the conflict. I guess the right place to solve this is in gst-plugins-bad010, which has a bug tracker at https://github.com/Homebrew/homebrew-versions/issues.
