### ISSUE TITLE
Update formula for Python 2 dependency for Python formula upgrade

### ISSUE THREAD

**Issue by d-g-h** [mopidy/homebrew-mopidy#21]
Remove depends_on "python" from formula?

> On 1st March 2018 the python formula will be upgraded to Python 3.x and a python@2 formula will be added for installing Python 2.7 (although this will be keg-only so neither python nor python2 will be added to the PATH by default without a manual brew link --force). We will maintain python2, python3 and python@3 aliases. **Any formulae that use depends_on "python" outside Homebrew/core will need to be updated at this point if they wish to keep using Python 2. Note: macOS has provided Python 2.7 since OS X Lion (10.7) so you can update formulae that need Python 2 today by removing depends_on "python" so they use the system python instead.**

Via https://brew.sh/2018/01/19/homebrew-1.5.0/

I'm having problems running mopidy now, if I'm the only one. Please close. If not, I can submit a PR. 
Reinstalled with `sudo pip2 install -U mopidy` in the meantime. Thanks.

**Comment by kiendang** [comment]
Agree. Since March 1, formulae `python` and `python@3` mean `python 3`, `python@2` means `python 2`. Maybe we should replace

    depends_on "python" => :recommended
    depends_on "python3" => :optional

to

    depends_on "python@2" => :recommended if MacOS.version <= :snow_leopard
    depends_on "python" => :optional
?

**Comment by jodal** [comment]
I'm open for either removing it or doing as @kiendang proposes. Please test it out and submit a PR with the solution you deem best.

**Comment by simmel** [comment]
Even that doesn't seem to fix it @kiendang since `python` is 3.6 from Homebrew.

If you change all `python` instances to `python2` that works but then the user has to have `/usr/local/opt/python@2/bin/` added to their `$PATH` AFACT...

Or change them to `python2.7` which implies system Python 2.7 but then we won't catch the `<= :snow_leopard` people...

**Comment by simmel** [comment]
Is this a problem any more since Homebrew is now following the correct versioning of Python (I can't remember the PEP for it)?
