### ISSUE TITLE
SHA256 Mismatch

### ISSUE THREAD

**Issue by vineyardbovines** [mopidy/homebrew-mopidy#25]
[crossposted](https://github.com/mopidy/mopidy-spotify/issues/180)

installing mopidy-spotify with homebrew fails with a sha256 mismatch--

```
Error: SHA256 mismatch
Expected: 80053f0779f6192a8052732904d88b91acc62a350831f6b585a3c6ac10cb8fbd
Actual: 5fc93fd7afbd094deb51d6fcbe147a406587f917c6be5682dd26525f9decdec6
Archive: /Users/sara/Library/Caches/Homebrew/libspotify-12.1.51.zip
```

i've tried to remove that zip, ran brew doctor and brew cleanup- no dice. other hacks to bypass sha256 errors with homebrew didn't work either.

all of the links to compile libspotify are dead, its been tossed around that its deprecated, risen again, etc. but i can't seem to find anything consistent.

the current workaround i have is to just manually put in the expected hash, but obviously not the best workaround

**Comment by jodal** [comment]
Fixed by af7c45be38b51e265bd6ef8d69448e2bc530efef
