### ISSUE TITLE
py2cairo not present or broken

### ISSUE THREAD

**Issue by RosalesJ** [mopidy/homebrew-mopidy#29]
During installation thorough brew

```brew install mopidy```

there was the error ```Error: /usr/local/opt/py2cairo not present or broken```

After running ```brew install py2cairo``` it was resolved, but it might be appropriate to add py2cairo as a dependency here.

**Comment by jodal** [comment]
Cairo isn't a direct dependency of Mopidy. It would be useful if anyone had the brew output including the lines above this error, so that we can see what formula was building when this happened.

**Comment by peritus** [comment]
Getting the same error, here with more context:

```
==> Summary
🍺  /usr/local/Cellar/python/3.7.0: 9,336 files, 160.2MB, built in 6 minutes 2 seconds
==> Installing mopidy/mopidy/mopidy dependency: py3cairo
==> Downloading https://homebrew.bintray.com/bottles/py3cairo-1.17.1.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring py3cairo-1.17.1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/py3cairo/1.17.1: 16 files, 305.7KB
==> Installing mopidy/mopidy/mopidy dependency: pygobject3
==> Downloading https://homebrew.bintray.com/bottles/pygobject3-3.28.3_1.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/47/47aa7d49c32d6805573f84732d9f0a1ff2d88547493b0d7ee2eaa09bdeacbdcb?__gda__=exp=1532696
######################################################################## 100.0%
==> Pouring pygobject3-3.28.3_1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pygobject3/3.28.3_1: 36 files, 2MB
==> Installing mopidy/mopidy/mopidy dependency: gst-python
Error: /usr/local/opt/py2cairo not present or broken
Please reinstall py2cairo. Sorry :(
```

**Comment by petewnr** [comment]
Got the same issue today.  With the same details.

**Comment by narze** [comment]
I got the same error as well

**Comment by narze** [comment]
I finally got it working by reinstalling py2cairo & pygobject3
https://gist.github.com/narze/ff41372d6b05558bf36b2597bf91f0c3

**Comment by jodal** [comment]
Quoting @narze's gist:

```
brew install python
# pygobject3 must be installed with --with-python@2 or it won't work
brew uninstall --ignore-dependencies pygobject3
brew install pygobject3 --with-python@2 gtk+3
brew install py2cairo # Another mopidy dependency
brew tap mopidy/mopidy
brew install mopidy
```

Thanks for a helpful step forwards with this!

### Dependency chain

As mentioned, Mopidy does not depend on py2cairo directly, and does not use py2cairo directly. The dependency chain is as follows:

[`mopidy`](https://github.com/mopidy/homebrew-mopidy/blob/master/Formula/mopidy.rb)
-> [`gst-python`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gst-python.rb)  (`without-python`, `with-python@2`)
-> [`pygobject3`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pygobject3.rb) (`with-python@2`)
-> [`py2cairo`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/py2cairo.rb)

### Thesis

My untested theory is that one can get in a situation where Homebrew regards Mopidy's dependencies as satisfied, but the dependencies haven't been built with the required build options. To me, the obvious way to get into this situation is to have gst-python and/or pygobject3 installed before installing Mopidy.

On a clean system, one should be able to reproduce with (untested):

```
brew install pygobject3
brew install mopidy/mopidy/mopidy
```

Beause `pyobject3` by default only installed `py3cairo`, not `py2cairo`, Mopidy now fails.

### Workaround

And then resolve the issue with (untested):

```
brew uninstall --ignore-dependencies gst-python pygobject3
brew install mopidy/mopidy/mopidy
```

### Proper solution

The question then is how the `mopidy` formula can be improved to make this an non-issue, without adding transitive dependencies directly to the `mopidy` formula.

**Comment by jodal** [comment]
The formulas in this tap have now been updated to run on Python 3. We no longer depend on the build options that were removed from the core Homebrew formulas almost a year ago.
