### ISSUE TITLE
Crashes after upgrading to Mopidy 1.0

### ISSUE THREAD

**Issue by jodal** [mopidy/homebrew-mopidy#3]
After upgrading from Mopidy 0.19.5 to 1.0 with `brew update && brew upgrade` I had several crashes when trying to list playlists or do searches because of missing methods on various backend classes.

The solution was to clean out all old `*.pyc` files in the Mopidy installation:

```
find /usr/local/lib/python2.7/site-packages/mopidy -name \*.pyc -delete
```

The formulas should be modified in some way so that this will not be an issue on future upgrades.

**Comment by jcass77** [comment]
Just a note that I also get this error when installing with `pip` in addition to `brew`.

Not sure why but I always need to delete the `*.pyc` files after doing a fresh install.

**Comment by jcass77** [comment]
...or maybe it just took me a few attempts to get the brew installation completely cleared out. Seems fine now.

**Comment by jodal** [comment]
https://discuss.mopidy.com/t/mopidy-cannot-start-with-attributeerror-has-no-attribute-ping/1038 looks like another case of this.
