### ISSUE TITLE
Mopidy install fails on gst-python@2 dependency

### ISSUE THREAD

**Issue by binoix** [mopidy/homebrew-mopidy#35]
Hi,

I tried to install Mopidy following troyxmccall's temporary workaround ([https://github.com/troyxmccall/homebrew-mopidy](https://github.com/troyxmccall/homebrew-mopidy)).

Installation fails while trying to install gst-python@2 dependency, as seen in the installation log below. 

> ==> Installing mopidy from troyxmccall/mopidy
> ==> Installing dependencies for troyxmccall/mopidy/mopidy: troyxmccall/mopidy/gst-python@2
> ==> Installing troyxmccall/mopidy/mopidy dependency: troyxmccall/mopidy/gst-python@2
> ==> Downloading https://homebrew.bintray.com/bottles-mopidy/gst-python@2-1.16.0.high_sierra.bottle.tar.gz
> 
> curl: (22) The requested URL returned error: 404 Not Found
> Error: Failed to download resource "gst-python@2"
> Download failed: https://homebrew.bintray.com/bottles-mopidy/gst-python@2-1.16.0.high_sierra.bottle.tar.gz
> Warning: Bottle installation failed: building from source.
> ==> Downloading https://gstreamer.freedesktop.org/src/gst-python/gst-python-1.16.0.tar.xz
> Already downloaded: /Users/benmar/Library/Caches/Homebrew/downloads/dd5865d78243265aad742ba638f9dee8e0e3885bb9462e20bf4b9440e8c4d281--gst-python-1.16.0.tar.xz
> ==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gst-python@2/1.16.0 --with-pygi-overrides-dir=/usr/local/Cellar/gst-python@2/1.16.0/lib/python2.7/site-packages/gi/overrides PYTHON=python
> Last 15 lines from /Users/benmar/Library/Logs/Homebrew/gst-python@2/01.configure:
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether UID '501' is supported by ustar format... yes
> checking whether GID '20' is supported by ustar format... yes
> checking how to create a ustar tar archive... gnutar
> checking nano version... 0 (release)
> checking whether to enable maintainer-specific portions of Makefiles... yes
> checking whether make supports nested variables... (cached) yes
> checking how to print strings... printf
> checking whether make supports the include directive... yes (GNU style)
> checking for gcc... clang
> checking whether the C compiler works... no
> configure: error: in `/private/tmp/gst-python@2-20190922-6747-8kyohm/gst-python-1.16.0':
> configure: error: C compiler cannot create executables
> See `config.log' for more details

I could not find config.log to dive into the problem.

Any idea?

Thanks

**Comment by jodal** [comment]
This tap has now been updated with pre-releases of Python 3.
