### ISSUE TITLE
SHA1 mismatch on two-lame dependency

### ISSUE THREAD

**Issue by oschrenk** [mopidy/homebrew-mopidy#4]
```
==> Installing mopidy-spotify dependency: two-lame
==> Downloading https://downloads.sourceforge.net/twolame/twolame-0.3.13.tar.gz
######################################################################## 100.0%
Error: SHA1 mismatch
Expected: 3ca460472c2f6eeedad70291d8e37da88b64eb8b
Actual: 4f7d85ce45bb48a93b5836ec35d0758262d29072
Archive: /Library/Caches/Homebrew/two-lame-0.3.13.tar.gz
To retry an incomplete download, remove the file above.
```

It's downloading an html page instead of the actual archive.

**Comment by jodal** [comment]
two-lame is part of the official Homebrew repo, ref. https://github.com/Homebrew/homebrew/blob/master/Library/Formula/two-lame.rb. Please open an issue there.

**Comment by oschrenk** [comment]
Thanks. It was actually an offending setting in my `.curlrc`. Opened an issue upstream https://github.com/Homebrew/homebrew/issues/39606
